options:
  install_sources:
    type: string
    default: "deb https://artifacts.elastic.co/packages/6.x/apt stable main"
    description: "Elastic Beats apt repository"
  install_keys:
    type: string
    default: D88E42B4
    description: "Elastic Beats apt repository key"
  logpath:
    type: string
    default: "/var/log/*.log /var/log/*/*.log"
    description: "Space separated log paths to monitor. Can contain wildcards."
  harvester_buffer_size:
    type: int
    default: 16384
    description: "Defines the buffer size every harvester uses when fetching the file"
  max_bytes:
    type: int
    default: 10485760
    description: "Maximum number of bytes a single log event can have. Default 10MB"
  exclude_files:
    type: string
    default: '["/filebeat.*", ".*gz$"]'
    description: |
      A list of regular expressions to match the files that you want Filebeat to ignore:
      https://www.elastic.co/guide/en/beats/filebeat/6.7/filebeat-input-log.html#filebeat-input-log-exclude-files"
  exclude_lines:
    type: string
    default: "[]"
    description: |
      A list of regular expressions to match the lines that you want Filebeat to exclude:
      https://www.elastic.co/guide/en/beats/filebeat/6.7/filebeat-input-log.html#filebeat-input-log-exclude-lines"
  fields:
    type: string
    default: ""
    description: "Space seperated list of key:value that the prospector will assign as field to each beat"
  kube_logs:
    type: boolean
    default: false
    description: |
      Whether or not to include the Kubernetes audit log as well as any K8s metadata
      when container logs are present on the system:
      https://www.elastic.co/guide/en/beats/filebeat/6.7/add-kubernetes-metadata.html

      Note: this option has no effect when related to a non Charmed Kubernetes charm.
  extra_inputs:
    type: string
    default: ""
    description: |
      A YAML list which will be injected to define additional prospectors/inputs.
